name: release

on:
  push:
    tags:
      - "*"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      build_version:
        description: '版本号'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up build args
      run: |
        echo "MAJOR_VERSION=${GITHUB_REF_NAME%%.*}" >> $GITHUB_ENV
        echo "MINOR_VERSION=${GITHUB_REF_NAME%.*}" >> $GITHUB_ENV
        echo "BUILD_VERSION=${{ github.event.inputs.build_version }}" >> $GITHUB_ENV
        echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        provenance: false
        tags: |
          docker.io/${{ secrets.DOCKER_USERNAME }}/iptv:${{ env.MAJOR_VERSION }}
          docker.io/${{ secrets.DOCKER_USERNAME }}/iptv:${{ env.MINOR_VERSION }}
          docker.io/${{ secrets.DOCKER_USERNAME }}/iptv:${{ env.BUILD_VERSION }}
          docker.io/${{ secrets.DOCKER_USERNAME }}/iptv:${{ env.TAG_VERSION }}
          docker.io/${{ secrets.DOCKER_USERNAME }}/iptv:latest


    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
